### ISSUE TITLE
您好，剪切板可以增加删除所有记录的功能吗，好像只能一条一条的删除

### ISSUE THREAD

**Issue by Hpxwd** [ipuppet/CAIO#89]
![E2DB7543-9255-470B-8365-261EFC708C6C](https://user-images.githubusercontent.com/113987466/201461422-07bc934b-88bf-4145-b178-5f4a895e80b3.png)
![7369803B-5935-4434-A827-49E4AD5F7966](https://user-images.githubusercontent.com/113987466/201461427-bb0f6576-0b31-4c49-a796-4b0382fca9f8.png)

**Comment by ipuppet** [comment]
目前可以在 "设置-文件管理" 中删除 `CAIO.db` 达到删除所有记录的目的，如果包含图片项目，同时删除 `image` 目录即可。
删除后重启脚本即可。后面可以加一个选项直接清除。

**Comment by ipuppet** [comment]
已经添加，在`设置-剪切板`中
